---
version: 12.3.2.1
slug: samba
name: Samba share
description: Expose Home Assistant folders with SMB/CIFS
url: https://github.com/Anatoli4www/hassio-repository-addon/tree/main/samba
codenotary: sitizenwww@gmail.com
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
host_network: true
#image: homeassistant/{arch}-addon-samba
init: false
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
  - /:rm
options:
  username: homeassistant
  password: null
  workgroup: WORKGROUP
  compatibility_mode: false
  veto_files:
    - ._*
    - .DS_Store
    - Thumbs.db
    - icon?
    - .Trashes
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
schema:
  username: str
  password: password
  workgroup: str
  compatibility_mode: bool
  veto_files:
    - str
  allow_hosts:
    - str
startup: services
